AllCops:
  NewCops: enable
  Exclude:
    - 'bin/bundle'
    - 'app/helpers/application_helper.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'
    - 'Gemfile'
    - 'db/shema.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'

Style/RegexpLiteral:
  EnforcedStyle: slashes

Metrics/MethodLength:
  Max: 20